//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.454
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payola.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payola.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum získání.
        /// </summary>
        public static string AcquirementDate {
            get {
                return ResourceManager.GetString("AcquirementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akce.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navázat.
        /// </summary>
        public static string AddRelation {
            get {
                return ResourceManager.GetString("AddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresy.
        /// </summary>
        public static string AddressPlural {
            get {
                return ResourceManager.GetString("AddressPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokročilé vyhledávání.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimálně jedna hodnota musí být zadána..
        /// </summary>
        public static string AllFieldsEmptyErrorMessage {
            get {
                return ResourceManager.GetString("AllFieldsEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimálně jedna hodnota musí být vyplněna..
        /// </summary>
        public static string AllPropertiesEmptyErrorMessage {
            get {
                return ResourceManager.GetString("AllPropertiesEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a navázat na.
        /// </summary>
        public static string AndAddRelationTo {
            get {
                return ResourceManager.GetString("AndAddRelationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anotace.
        /// </summary>
        public static string Annotation {
            get {
                return ResourceManager.GetString("Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předčíslí.
        /// </summary>
        public static string AnteNumber {
            get {
                return ResourceManager.GetString("AnteNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na detail.
        /// </summary>
        public static string BackToDetail {
            get {
                return ResourceManager.GetString("BackToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na přehled vazby.
        /// </summary>
        public static string BackToRelation {
            get {
                return ResourceManager.GetString("BackToRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Základní kapitál.
        /// </summary>
        public static string BasicCapital {
            get {
                return ResourceManager.GetString("BasicCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navázat.
        /// </summary>
        public static string Bind {
            get {
                return ResourceManager.GetString("Bind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum narození.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné příjmení.
        /// </summary>
        public static string BirthSurname {
            get {
                return ResourceManager.GetString("BirthSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Značka.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státní občanství.
        /// </summary>
        public static string Citizenships {
            get {
                return ResourceManager.GetString("Citizenships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřít.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřít tuto událost.
        /// </summary>
        public static string CloseIncident {
            get {
                return ResourceManager.GetString("CloseIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřít tuto zprávu.
        /// </summary>
        public static string CloseReport {
            get {
                return ResourceManager.GetString("CloseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavření události.
        /// </summary>
        public static string ClosingIncident {
            get {
                return ResourceManager.GetString("ClosingIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barva.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentář.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Společnost.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sídlí na adresách.
        /// </summary>
        public static string CompanyHasAddress {
            get {
                return ResourceManager.GetString("CompanyHasAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je sídlem společností.
        /// </summary>
        public static string CompanyHasAddressInverse {
            get {
                return ResourceManager.GetString("CompanyHasAddressInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má společníky.
        /// </summary>
        public static string CompanyHasAssociate {
            get {
                return ResourceManager.GetString("CompanyHasAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je společníkem ve společnostech.
        /// </summary>
        public static string CompanyHasAssociateInverse {
            get {
                return ResourceManager.GetString("CompanyHasAssociateInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má členy představenstva.
        /// </summary>
        public static string CompanyHasDirector {
            get {
                return ResourceManager.GetString("CompanyHasDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je členem představenstva společností.
        /// </summary>
        public static string CompanyHasDirectorInverse {
            get {
                return ResourceManager.GetString("CompanyHasDirectorInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používá e-maily.
        /// </summary>
        public static string CompanyHasEmail {
            get {
                return ResourceManager.GetString("CompanyHasEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je používán společnostmi.
        /// </summary>
        public static string CompanyHasEmailInverse {
            get {
                return ResourceManager.GetString("CompanyHasEmailInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má jednatele.
        /// </summary>
        public static string CompanyHasExecutive {
            get {
                return ResourceManager.GetString("CompanyHasExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je jednatelem společností.
        /// </summary>
        public static string CompanyHasExecutiveInverse {
            get {
                return ResourceManager.GetString("CompanyHasExecutiveInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní telefony.
        /// </summary>
        public static string CompanyHasPhone {
            get {
                return ResourceManager.GetString("CompanyHasPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je vlastněn společnostmi.
        /// </summary>
        public static string CompanyHasPhoneInverse {
            get {
                return ResourceManager.GetString("CompanyHasPhoneInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má členy dozorčí rady.
        /// </summary>
        public static string CompanyHasSupervisor {
            get {
                return ResourceManager.GetString("CompanyHasSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je členem dozorčí rady společností.
        /// </summary>
        public static string CompanyHasSupervisorInverse {
            get {
                return ResourceManager.GetString("CompanyHasSupervisorInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastní vozidla.
        /// </summary>
        public static string CompanyHasVehicle {
            get {
                return ResourceManager.GetString("CompanyHasVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je vlastněno společnostmi.
        /// </summary>
        public static string CompanyHasVehicleInverse {
            get {
                return ResourceManager.GetString("CompanyHasVehicleInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Společnosti.
        /// </summary>
        public static string CompanyPlural {
            get {
                return ResourceManager.GetString("CompanyPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stát.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou adresu.
        /// </summary>
        public static string CreateAddress {
            get {
                return ResourceManager.GetString("CreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit a navázat.
        /// </summary>
        public static string CreateAndAddRelation {
            get {
                return ResourceManager.GetString("CreateAndAddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou společnost.
        /// </summary>
        public static string CreateCompany {
            get {
                return ResourceManager.GetString("CreateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit nový e-mail.
        /// </summary>
        public static string CreateEmail {
            get {
                return ResourceManager.GetString("CreateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou událost.
        /// </summary>
        public static string CreateIncident {
            get {
                return ResourceManager.GetString("CreateIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou informaci.
        /// </summary>
        public static string CreateInformation {
            get {
                return ResourceManager.GetString("CreateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit nové klíčové slovo.
        /// </summary>
        public static string CreateKeyword {
            get {
                return ResourceManager.GetString("CreateKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou osobu.
        /// </summary>
        public static string CreatePerson {
            get {
                return ResourceManager.GetString("CreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit nový telefon.
        /// </summary>
        public static string CreatePhone {
            get {
                return ResourceManager.GetString("CreatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novou zprávu.
        /// </summary>
        public static string CreateReport {
            get {
                return ResourceManager.GetString("CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit nový útvar StB.
        /// </summary>
        public static string CreateStbDivision {
            get {
                return ResourceManager.GetString("CreateStbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit nové vozidlo.
        /// </summary>
        public static string CreateVehicle {
            get {
                return ResourceManager.GetString("CreateVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Důvěryhodnost.
        /// </summary>
        public static string Credibility {
            get {
                return ResourceManager.GetString("Credibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pochybná, ale možná pravdivá.
        /// </summary>
        public static string CredibilityDoubtfulButMaybeTrue {
            get {
                return ResourceManager.GetString("CredibilityDoubtfulButMaybeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravděpodobně pravdivá.
        /// </summary>
        public static string CredibilityLikelyTrue {
            get {
                return ResourceManager.GetString("CredibilityLikelyTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asi pravdivá.
        /// </summary>
        public static string CredibilityMaybeTrue {
            get {
                return ResourceManager.GetString("CredibilityMaybeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pravdivá.
        /// </summary>
        public static string CredibilityTrue {
            get {
                return ResourceManager.GetString("CredibilityTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze posoudit.
        /// </summary>
        public static string CredibilityUnableToAssess {
            get {
                return ResourceManager.GetString("CredibilityUnableToAssess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepravděpodobná.
        /// </summary>
        public static string CredibilityUnlikelyTrue {
            get {
                return ResourceManager.GetString("CredibilityUnlikelyTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toto pole obsahuje neplatnou hodnotu..
        /// </summary>
        public static string DataTypeAttributeErrorMessage {
            get {
                return ResourceManager.GetString("DataTypeAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas publikace.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly před jménem.
        /// </summary>
        public static string DegreesAheadName {
            get {
                return ResourceManager.GetString("DegreesAheadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tituly za jménem.
        /// </summary>
        public static string DegreesBehindName {
            get {
                return ResourceManager.GetString("DegreesBehindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto adresu.
        /// </summary>
        public static string DeleteAddress {
            get {
                return ResourceManager.GetString("DeleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto společnost.
        /// </summary>
        public static string DeleteCompany {
            get {
                return ResourceManager.GetString("DeleteCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tento e-mail.
        /// </summary>
        public static string DeleteEmail {
            get {
                return ResourceManager.GetString("DeleteEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto událost.
        /// </summary>
        public static string DeleteIncident {
            get {
                return ResourceManager.GetString("DeleteIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto informaci.
        /// </summary>
        public static string DeleteInformation {
            get {
                return ResourceManager.GetString("DeleteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto osobu.
        /// </summary>
        public static string DeletePerson {
            get {
                return ResourceManager.GetString("DeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tento telefon.
        /// </summary>
        public static string DeletePhone {
            get {
                return ResourceManager.GetString("DeletePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat vazbu.
        /// </summary>
        public static string DeleteRelation {
            get {
                return ResourceManager.GetString("DeleteRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tuto zprávu.
        /// </summary>
        public static string DeleteReport {
            get {
                return ResourceManager.GetString("DeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat tento útvar StB.
        /// </summary>
        public static string DeleteStbDivision {
            get {
                return ResourceManager.GetString("DeleteStbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat toto vozidlo.
        /// </summary>
        public static string DeleteVehicle {
            get {
                return ResourceManager.GetString("DeleteVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto adresu.
        /// </summary>
        public static string EditAddress {
            get {
                return ResourceManager.GetString("EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto společnost.
        /// </summary>
        public static string EditCompany {
            get {
                return ResourceManager.GetString("EditCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tento e-mail.
        /// </summary>
        public static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto událost.
        /// </summary>
        public static string EditIncident {
            get {
                return ResourceManager.GetString("EditIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto informaci.
        /// </summary>
        public static string EditInformation {
            get {
                return ResourceManager.GetString("EditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto osobu.
        /// </summary>
        public static string EditPerson {
            get {
                return ResourceManager.GetString("EditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tento telefon.
        /// </summary>
        public static string EditPhone {
            get {
                return ResourceManager.GetString("EditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit tuto zprávu.
        /// </summary>
        public static string EditReport {
            get {
                return ResourceManager.GetString("EditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit útvar StB.
        /// </summary>
        public static string EditStbDivision {
            get {
                return ResourceManager.GetString("EditStbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit toto vozidlo.
        /// </summary>
        public static string EditVehicle {
            get {
                return ResourceManager.GetString("EditVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail adresa.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-maily.
        /// </summary>
        public static string EmailPlural {
            get {
                return ResourceManager.GetString("EmailPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis uzavření.
        /// </summary>
        public static string EnclosureDescription {
            get {
                return ResourceManager.GetString("EnclosureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armáda.
        /// </summary>
        public static string FieldArmy {
            get {
                return ResourceManager.GetString("FieldArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samospráva.
        /// </summary>
        public static string FieldAutonomy {
            get {
                return ResourceManager.GetString("FieldAutonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankovnictví.
        /// </summary>
        public static string FieldBanking {
            get {
                return ResourceManager.GetString("FieldBanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizační složka ministerstva.
        /// </summary>
        public static string FieldBranchOfMinistry {
            get {
                return ResourceManager.GetString("FieldBranchOfMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslanecká sněmovna.
        /// </summary>
        public static string FieldChamberOfDeputies {
            get {
                return ResourceManager.GetString("FieldChamberOfDeputies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soud.
        /// </summary>
        public static string FieldCourt {
            get {
                return ResourceManager.GetString("FieldCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vláda.
        /// </summary>
        public static string FieldGovernment {
            get {
                return ResourceManager.GetString("FieldGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdravotnictví.
        /// </summary>
        public static string FieldHealth {
            get {
                return ResourceManager.GetString("FieldHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministerstvo.
        /// </summary>
        public static string FieldMinistry {
            get {
                return ResourceManager.GetString("FieldMinistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiný subjekt.
        /// </summary>
        public static string FieldOther {
            get {
                return ResourceManager.GetString("FieldOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiný ústřední orgán.
        /// </summary>
        public static string FieldOtherCentralAuthority {
            get {
                return ResourceManager.GetString("FieldOtherCentralAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policie.
        /// </summary>
        public static string FieldPolice {
            get {
                return ResourceManager.GetString("FieldPolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezident.
        /// </summary>
        public static string FieldPresident {
            get {
                return ResourceManager.GetString("FieldPresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státní zastupitelství.
        /// </summary>
        public static string FieldProsecution {
            get {
                return ResourceManager.GetString("FieldProsecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obor.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senát.
        /// </summary>
        public static string FieldSenate {
            get {
                return ResourceManager.GetString("FieldSenate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizace s majetkovou účastí státu.
        /// </summary>
        public static string FieldStateCapitalOrganization {
            get {
                return ResourceManager.GetString("FieldStateCapitalOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má adresy.
        /// </summary>
        public static string HasAddress {
            get {
                return ResourceManager.GetString("HasAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo orientační.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Událost.
        /// </summary>
        public static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Událost je uzavřena.
        /// </summary>
        public static string IncidentClosed {
            get {
                return ResourceManager.GetString("IncidentClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souvisí s informacemi.
        /// </summary>
        public static string IncidentHasRelatedInformation {
            get {
                return ResourceManager.GetString("IncidentHasRelatedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Události.
        /// </summary>
        public static string IncidentPlural {
            get {
                return ResourceManager.GetString("IncidentPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřená.
        /// </summary>
        public static string IncidentStateClosed {
            get {
                return ResourceManager.GetString("IncidentStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřená.
        /// </summary>
        public static string IncidentStateOpen {
            get {
                return ResourceManager.GetString("IncidentStateOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souvisí s událostmi.
        /// </summary>
        public static string InformationHasRelatedIncident {
            get {
                return ResourceManager.GetString("InformationHasRelatedIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o adresách.
        /// </summary>
        public static string InformationMentionsAddress {
            get {
                return ResourceManager.GetString("InformationMentionsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsažena v informacích.
        /// </summary>
        public static string InformationMentionsAddressInverse {
            get {
                return ResourceManager.GetString("InformationMentionsAddressInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o společnostech.
        /// </summary>
        public static string InformationMentionsCompany {
            get {
                return ResourceManager.GetString("InformationMentionsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsažena v informacích.
        /// </summary>
        public static string InformationMentionsCompanyInverse {
            get {
                return ResourceManager.GetString("InformationMentionsCompanyInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o e-mailech.
        /// </summary>
        public static string InformationMentionsEmail {
            get {
                return ResourceManager.GetString("InformationMentionsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsažen v informacích.
        /// </summary>
        public static string InformationMentionsEmailInverse {
            get {
                return ResourceManager.GetString("InformationMentionsEmailInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o osobách.
        /// </summary>
        public static string InformationMentionsPerson {
            get {
                return ResourceManager.GetString("InformationMentionsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsažena v informacích.
        /// </summary>
        public static string InformationMentionsPersonInverse {
            get {
                return ResourceManager.GetString("InformationMentionsPersonInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o telefonech.
        /// </summary>
        public static string InformationMentionsPhone {
            get {
                return ResourceManager.GetString("InformationMentionsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsažen v informacích.
        /// </summary>
        public static string InformationMentionsPhoneInverse {
            get {
                return ResourceManager.GetString("InformationMentionsPhoneInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pojednává o vozidlech.
        /// </summary>
        public static string InformationMentionsVehicle {
            get {
                return ResourceManager.GetString("InformationMentionsVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je obsaženo v informacích.
        /// </summary>
        public static string InformationMentionsVehicleInverse {
            get {
                return ResourceManager.GetString("InformationMentionsVehicleInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informace.
        /// </summary>
        public static string InformationPlural {
            get {
                return ResourceManager.GetString("InformationPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze ověřit.
        /// </summary>
        public static string InformationStateUnverifiable {
            get {
                return ResourceManager.GetString("InformationStateUnverifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neověřeno.
        /// </summary>
        public static string InformationStateUnverified {
            get {
                return ResourceManager.GetString("InformationStateUnverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá ověřování.
        /// </summary>
        public static string InformationStateVerificationInProgress {
            get {
                return ResourceManager.GetString("InformationStateVerificationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověřeno.
        /// </summary>
        public static string InformationStateVerified {
            get {
                return ResourceManager.GetString("InformationStateVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsahuje klíčová slova.
        /// </summary>
        public static string InformativeEntityContainsKeyword {
            get {
                return ResourceManager.GetString("InformativeEntityContainsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vložení.
        /// </summary>
        public static string InsertionDate {
            get {
                return ResourceManager.GetString("InsertionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikovatelná.
        /// </summary>
        public static string IsPublishable {
            get {
                return ResourceManager.GetString("IsPublishable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klíčové slovo.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klíčová slova.
        /// </summary>
        public static string KeywordPlural {
            get {
                return ResourceManager.GetString("KeywordPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klíčová slova.
        /// </summary>
        public static string KeywordsValue {
            get {
                return ResourceManager.GetString("KeywordsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druh.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo popisné.
        /// </summary>
        public static string LandRegistryNumber {
            get {
                return ResourceManager.GetString("LandRegistryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPZ.
        /// </summary>
        public static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výrobce.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodinný stav.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozvedený/Rozvedená.
        /// </summary>
        public static string MaritalStatusDivorced {
            get {
                return ResourceManager.GetString("MaritalStatusDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženatý/Vdaná.
        /// </summary>
        public static string MaritalStatusMarried {
            get {
                return ResourceManager.GetString("MaritalStatusMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svobodný/Svobodná.
        /// </summary>
        public static string MaritalStatusSingle {
            get {
                return ResourceManager.GetString("MaritalStatusSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovdovělý/Ovdovělá.
        /// </summary>
        public static string MaritalStatusWidowed {
            get {
                return ResourceManager.GetString("MaritalStatusWidowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text v tomto poli nesmí být delší než {1} znaků..
        /// </summary>
        public static string MaxLengthAttributeErrorMessage {
            get {
                return ResourceManager.GetString("MaxLengthAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Národnost.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámá.
        /// </summary>
        public static string NationalityUnknown {
            get {
                return ResourceManager.GetString("NationalityUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová adresa.
        /// </summary>
        public static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová společnost.
        /// </summary>
        public static string NewCompany {
            get {
                return ResourceManager.GetString("NewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová událost.
        /// </summary>
        public static string NewIncident {
            get {
                return ResourceManager.GetString("NewIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová informace.
        /// </summary>
        public static string NewInformation {
            get {
                return ResourceManager.GetString("NewInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová osoba.
        /// </summary>
        public static string NewPerson {
            get {
                return ResourceManager.GetString("NewPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový telefon.
        /// </summary>
        public static string NewPhone {
            get {
                return ResourceManager.GetString("NewPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nová zpráva.
        /// </summary>
        public static string NewReport {
            get {
                return ResourceManager.GetString("NewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový útvar StB.
        /// </summary>
        public static string NewStbDivision {
            get {
                return ResourceManager.GetString("NewStbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové vozidlo.
        /// </summary>
        public static string NewVehicle {
            get {
                return ResourceManager.GetString("NewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žádné navázané.
        /// </summary>
        public static string NoRelated {
            get {
                return ResourceManager.GetString("NoRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurčeno.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ objektu v relaci.
        /// </summary>
        public static string ObjectiveTypeName {
            get {
                return ResourceManager.GetString("ObjectiveTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít tuto událost.
        /// </summary>
        public static string OpenIncident {
            get {
                return ResourceManager.GetString("OpenIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otevřít tuto zprávu.
        /// </summary>
        public static string OpenReport {
            get {
                return ResourceManager.GetString("OpenReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vzniku.
        /// </summary>
        public static string OriginDate {
            get {
                return ResourceManager.GetString("OriginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok založení.
        /// </summary>
        public static string OriginYear {
            get {
                return ResourceManager.GetString("OriginYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodné číslo.
        /// </summary>
        public static string PersonalIdentificationNumber {
            get {
                return ResourceManager.GetString("PersonalIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má místa narození.
        /// </summary>
        public static string PersonHasBirthAddress {
            get {
                return ResourceManager.GetString("PersonHasBirthAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je místem narození osob.
        /// </summary>
        public static string PersonHasBirthAddressInverse {
            get {
                return ResourceManager.GetString("PersonHasBirthAddressInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má obchodní partnery.
        /// </summary>
        public static string PersonHasBusinessPartner {
            get {
                return ResourceManager.GetString("PersonHasBusinessPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spolupracuje s osobami.
        /// </summary>
        public static string PersonHasColleague {
            get {
                return ResourceManager.GetString("PersonHasColleague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má rodiče.
        /// </summary>
        public static string PersonHasParent {
            get {
                return ResourceManager.GetString("PersonHasParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má nevlastní rodiče.
        /// </summary>
        public static string PersonHasParentInLaw {
            get {
                return ResourceManager.GetString("PersonHasParentInLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má nevlastní děti.
        /// </summary>
        public static string PersonHasParentInLawInverse {
            get {
                return ResourceManager.GetString("PersonHasParentInLawInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má děti.
        /// </summary>
        public static string PersonHasParentInverse {
            get {
                return ResourceManager.GetString("PersonHasParentInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má partnery.
        /// </summary>
        public static string PersonHasPartner {
            get {
                return ResourceManager.GetString("PersonHasPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má trvalá bydliště.
        /// </summary>
        public static string PersonHasResidence {
            get {
                return ResourceManager.GetString("PersonHasResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je trvalým bydlištěm osob.
        /// </summary>
        public static string PersonHasResidenceInverse {
            get {
                return ResourceManager.GetString("PersonHasResidenceInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má místa pobytu.
        /// </summary>
        public static string PersonHasWhereabouts {
            get {
                return ResourceManager.GetString("PersonHasWhereabouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je místem pobytu osob.
        /// </summary>
        public static string PersonHasWhereaboutsInverse {
            get {
                return ResourceManager.GetString("PersonHasWhereaboutsInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je v manželství s osobami.
        /// </summary>
        public static string PersonIsInMarriage {
            get {
                return ResourceManager.GetString("PersonIsInMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoby.
        /// </summary>
        public static string PersonPlural {
            get {
                return ResourceManager.GetString("PersonPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používá e-maily.
        /// </summary>
        public static string PersonUsesEmail {
            get {
                return ResourceManager.GetString("PersonUsesEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je používán osobami.
        /// </summary>
        public static string PersonUsesEmailInverse {
            get {
                return ResourceManager.GetString("PersonUsesEmailInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používá telefony.
        /// </summary>
        public static string PersonUsesPhone {
            get {
                return ResourceManager.GetString("PersonUsesPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je používán osobami.
        /// </summary>
        public static string PersonUsesPhoneInverse {
            get {
                return ResourceManager.GetString("PersonUsesPhoneInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používá vozidla.
        /// </summary>
        public static string PersonUsesVehicle {
            get {
                return ResourceManager.GetString("PersonUsesVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je používáno osobami.
        /// </summary>
        public static string PersonUsesVehicleInverse {
            get {
                return ResourceManager.GetString("PersonUsesVehicleInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefony.
        /// </summary>
        public static string PhonePlural {
            get {
                return ResourceManager.GetString("PhonePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Místo publikace.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnosti vazby mezi.
        /// </summary>
        public static string PropertiesOfRelationBetween {
            get {
                return ResourceManager.GetString("PropertiesOfRelationBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota tohoto pole je neplatná..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikace.
        /// </summary>
        public static string PublicationPlural {
            get {
                return ResourceManager.GetString("PublicationPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled publikací události.
        /// </summary>
        public static string PublicationsOfIncident {
            get {
                return ResourceManager.GetString("PublicationsOfIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled publikací informace.
        /// </summary>
        public static string PublicationsOfInformation {
            get {
                return ResourceManager.GetString("PublicationsOfInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled publikací zprávy.
        /// </summary>
        public static string PublicationsOfReport {
            get {
                return ResourceManager.GetString("PublicationsOfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikovat.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikovat tuto událost.
        /// </summary>
        public static string PublishIncident {
            get {
                return ResourceManager.GetString("PublishIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikovat tuto informaci.
        /// </summary>
        public static string PublishInformation {
            get {
                return ResourceManager.GetString("PublishInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikace události.
        /// </summary>
        public static string PublishingIncident {
            get {
                return ResourceManager.GetString("PublishingIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikace informace.
        /// </summary>
        public static string PublishingInformation {
            get {
                return ResourceManager.GetString("PublishingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikace zprávy.
        /// </summary>
        public static string PublishingReport {
            get {
                return ResourceManager.GetString("PublishingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publikovat tuto zprávu.
        /// </summary>
        public static string PublishReport {
            get {
                return ResourceManager.GetString("PublishReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Středočeský kraj.
        /// </summary>
        public static string RegionCentralBohemian {
            get {
                return ResourceManager.GetString("RegionCentralBohemian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahraničí.
        /// </summary>
        public static string RegionForeign {
            get {
                return ResourceManager.GetString("RegionForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Královéhradecký kraj.
        /// </summary>
        public static string RegionHradecKralove {
            get {
                return ResourceManager.GetString("RegionHradecKralove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karlovarský kraj.
        /// </summary>
        public static string RegionKarlovyVary {
            get {
                return ResourceManager.GetString("RegionKarlovyVary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberecký kraj.
        /// </summary>
        public static string RegionLiberec {
            get {
                return ResourceManager.GetString("RegionLiberec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moravskoslezský kraj.
        /// </summary>
        public static string RegionMoravianSilesian {
            get {
                return ResourceManager.GetString("RegionMoravianSilesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olomoucký kraj.
        /// </summary>
        public static string RegionOlomouc {
            get {
                return ResourceManager.GetString("RegionOlomouc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string RegionOther {
            get {
                return ResourceManager.GetString("RegionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardubický kraj.
        /// </summary>
        public static string RegionPardubice {
            get {
                return ResourceManager.GetString("RegionPardubice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plzeňský kraj.
        /// </summary>
        public static string RegionPlzen {
            get {
                return ResourceManager.GetString("RegionPlzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavní město Praha.
        /// </summary>
        public static string RegionPrague {
            get {
                return ResourceManager.GetString("RegionPrague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Působnost.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jihočeský kraj.
        /// </summary>
        public static string RegionSouthBohemian {
            get {
                return ResourceManager.GetString("RegionSouthBohemian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jihomoravský kraj.
        /// </summary>
        public static string RegionSouthMoravian {
            get {
                return ResourceManager.GetString("RegionSouthMoravian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ústecký kraj.
        /// </summary>
        public static string RegionUstiNadLabem {
            get {
                return ResourceManager.GetString("RegionUstiNadLabem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj Vysočina.
        /// </summary>
        public static string RegionVysocina {
            get {
                return ResourceManager.GetString("RegionVysocina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlínský kraj.
        /// </summary>
        public static string RegionZlin {
            get {
                return ResourceManager.GetString("RegionZlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zápisu.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČ.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navázané.
        /// </summary>
        public static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazby.
        /// </summary>
        public static string Relations {
            get {
                return ResourceManager.GetString("Relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpráva.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpráva je uzavřena.
        /// </summary>
        public static string ReportClosed {
            get {
                return ResourceManager.GetString("ReportClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisuje události.
        /// </summary>
        public static string ReportDescribesIncident {
            get {
                return ResourceManager.GetString("ReportDescribesIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popisuje informace.
        /// </summary>
        public static string ReportDescribesInformation {
            get {
                return ResourceManager.GetString("ReportDescribesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediální.
        /// </summary>
        public static string ReportKindMedia {
            get {
                return ResourceManager.GetString("ReportKindMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiná.
        /// </summary>
        public static string ReportKindOther {
            get {
                return ResourceManager.GetString("ReportKindOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výstupní.
        /// </summary>
        public static string ReportKindOutput {
            get {
                return ResourceManager.GetString("ReportKindOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehledová.
        /// </summary>
        public static string ReportKindOverview {
            get {
                return ResourceManager.GetString("ReportKindOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situační.
        /// </summary>
        public static string ReportKindSituational {
            get {
                return ResourceManager.GetString("ReportKindSituational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podkladová.
        /// </summary>
        public static string ReportKindUnderlying {
            get {
                return ResourceManager.GetString("ReportKindUnderlying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zprávy.
        /// </summary>
        public static string ReportPlural {
            get {
                return ResourceManager.GetString("ReportPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzavřená.
        /// </summary>
        public static string ReportStateClosed {
            get {
                return ResourceManager.GetString("ReportStateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koncept.
        /// </summary>
        public static string ReportStateConcept {
            get {
                return ResourceManager.GetString("ReportStateConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota musí být zadána..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toto pole musí být vyplněno..
        /// </summary>
        public static string RequiredAttributeErrorMessage {
            get {
                return ResourceManager.GetString("RequiredAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledat.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pohlaví.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žena.
        /// </summary>
        public static string SexFemale {
            get {
                return ResourceManager.GetString("SexFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muž.
        /// </summary>
        public static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdroj.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string SourceInternet {
            get {
                return ResourceManager.GetString("SourceInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literatura.
        /// </summary>
        public static string SourceLiterature {
            get {
                return ResourceManager.GetString("SourceLiterature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neurčeno.
        /// </summary>
        public static string SourceNotSpecified {
            get {
                return ResourceManager.GetString("SourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jiný.
        /// </summary>
        public static string SourceOther {
            get {
                return ResourceManager.GetString("SourceOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyzická osoba.
        /// </summary>
        public static string SourcePerson {
            get {
                return ResourceManager.GetString("SourcePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tisk.
        /// </summary>
        public static string SourcePress {
            get {
                return ResourceManager.GetString("SourcePress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rádio.
        /// </summary>
        public static string SourceRadio {
            get {
                return ResourceManager.GetString("SourceRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Televize.
        /// </summary>
        public static string SourceTelevision {
            get {
                return ResourceManager.GetString("SourceTelevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jako správa StB evidovala osoby.
        /// </summary>
        public static string StbAdministrationRegisteredPerson {
            get {
                return ResourceManager.GetString("StbAdministrationRegisteredPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byla evidována u správ StB.
        /// </summary>
        public static string StbAdministrationRegisteredPersonInverse {
            get {
                return ResourceManager.GetString("StbAdministrationRegisteredPersonInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jako odbor StB evidoval osoby.
        /// </summary>
        public static string StbDepartmentRegisteredPerson {
            get {
                return ResourceManager.GetString("StbDepartmentRegisteredPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byl evidována u odborů StB.
        /// </summary>
        public static string StbDepartmentRegisteredPersonInverse {
            get {
                return ResourceManager.GetString("StbDepartmentRegisteredPersonInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útvar StB.
        /// </summary>
        public static string StbDivision {
            get {
                return ResourceManager.GetString("StbDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Útvary StB.
        /// </summary>
        public static string StbDivisionPlural {
            get {
                return ResourceManager.GetString("StbDivisionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platnost od.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platnost do.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozidlo.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkovalo na adresách.
        /// </summary>
        public static string VehicleParkedOnAddress {
            get {
                return ResourceManager.GetString("VehicleParkedOnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byla zde zaparkována vozidla.
        /// </summary>
        public static string VehicleParkedOnAddressInverse {
            get {
                return ResourceManager.GetString("VehicleParkedOnAddressInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vozidla.
        /// </summary>
        public static string VehiclePlural {
            get {
                return ResourceManager.GetString("VehiclePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítá vás Payola!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
